name: Playwright test
on:
  push:
    branches: [ my-full-featured ]
  pull_request:
    branches: [ my-full-featured ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble
      options: --network host
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm install
    - run: npm test

