name: Playwright test
on:
  push:
    branches: [ my-full-featured ]
  pull_request:
    branches: [ my-full-featured ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - run: npm install
    - run: cp node_modules/pako/dist/pako_inflate.es5.min.js extension/
    - run: wget -P testpage https://tamo.github.io/dict/SKK-JISYO.L.gz
    - run: npm test

